version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: gosocial-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gosocial_test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    image: mongo:6.0
    container_name: gosocial-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mysql_data:
  mongo_data:
