version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: gosocial_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: gosocial
    volumes:
      - mongodb_data:/data/db
    networks:
      gosocial_network:
        ipv4_address: 172.20.0.10

  mongo-express:
    image: mongo-express:latest
    container_name: gosocial_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: 172.20.0.10  # Use MongoDB's static IP
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      gosocial_network:
        ipv4_address: 172.20.0.11

#  media-server:
#    build:
#      context: .
#      dockerfile: cmd/media-server/Dockerfile
#    container_name: gosocial_media_server
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      MONGO_HOST: 172.20.0.10
#      MONGO_PORT: 27017
#      MONGO_USERNAME: admin
#      MONGO_PASSWORD: admin123
#      MONGO_DATABASE: gosocial
#      MEDIA_SERVER_PORT: 8080
#      MEDIA_BASE_URL: http://localhost:8080/media
#    depends_on:
#      - mongodb
#    networks:
#      gosocial_network:
#        ipv4_address: 172.20.0.20

volumes:
  mongodb_data:
    driver: local

networks:
  gosocial_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

