// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: feed.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Content struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ContentId     int64                   `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	AuthorId      int64                   `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Type          string                  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "POST", "STORY", "REEL"
	TextContent   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	MediaRefId    *wrapperspb.Int64Value  `protobuf:"bytes,5,opt,name=media_ref_id,json=mediaRefId,proto3" json:"media_ref_id,omitempty"`
	Privacy       string                  `protobuf:"bytes,6,opt,name=privacy,proto3" json:"privacy,omitempty"` // "public", "friends", "private"
	Expiration    *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Duration      *wrapperspb.Int32Value  `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Content) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Content) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Content) GetTextContent() *wrapperspb.StringValue {
	if x != nil {
		return x.TextContent
	}
	return nil
}

func (x *Content) GetMediaRefId() *wrapperspb.Int64Value {
	if x != nil {
		return x.MediaRefId
	}
	return nil
}

func (x *Content) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *Content) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *Content) GetDuration() *wrapperspb.Int32Value {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Content) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Content) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateContentRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AuthorId      int64                   `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Type          string                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TextContent   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	MediaRefId    *wrapperspb.Int64Value  `protobuf:"bytes,4,opt,name=media_ref_id,json=mediaRefId,proto3" json:"media_ref_id,omitempty"`
	Privacy       string                  `protobuf:"bytes,5,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Expiration    *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Duration      *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContentRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateContentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateContentRequest) GetTextContent() *wrapperspb.StringValue {
	if x != nil {
		return x.TextContent
	}
	return nil
}

func (x *CreateContentRequest) GetMediaRefId() *wrapperspb.Int64Value {
	if x != nil {
		return x.MediaRefId
	}
	return nil
}

func (x *CreateContentRequest) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *CreateContentRequest) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *CreateContentRequest) GetDuration() *wrapperspb.Int32Value {
	if x != nil {
		return x.Duration
	}
	return nil
}

type ContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentResponse) Reset() {
	*x = ContentResponse{}
	mi := &file_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentResponse) ProtoMessage() {}

func (x *ContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentResponse.ProtoReflect.Descriptor instead.
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{2}
}

func (x *ContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type DeleteContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentRequest) Reset() {
	*x = DeleteContentRequest{}
	mi := &file_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentRequest) ProtoMessage() {}

func (x *DeleteContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentRequest.ProtoReflect.Descriptor instead.
func (*DeleteContentRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteContentRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type DeleteContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentResponse) Reset() {
	*x = DeleteContentResponse{}
	mi := &file_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentResponse) ProtoMessage() {}

func (x *DeleteContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentResponse.ProtoReflect.Descriptor instead.
func (*DeleteContentResponse) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListUserContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserContentRequest) Reset() {
	*x = ListUserContentRequest{}
	mi := &file_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserContentRequest) ProtoMessage() {}

func (x *ListUserContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserContentRequest.ProtoReflect.Descriptor instead.
func (*ListUserContentRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserContentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListUserContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Content             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserContentResponse) Reset() {
	*x = ListUserContentResponse{}
	mi := &file_feed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserContentResponse) ProtoMessage() {}

func (x *ListUserContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserContentResponse.ProtoReflect.Descriptor instead.
func (*ListUserContentResponse) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserContentResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_feed_proto protoreflect.FileDescriptor

const file_feed_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"feed.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xde\x03\n" +
	"\aContent\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12?\n" +
	"\ftext_content\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vtextContent\x12=\n" +
	"\fmedia_ref_id\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"mediaRefId\x12\x18\n" +
	"\aprivacy\x18\x06 \x01(\tR\aprivacy\x12:\n" +
	"\n" +
	"expiration\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x127\n" +
	"\bduration\x18\b \x01(\v2\x1b.google.protobuf.Int32ValueR\bduration\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd6\x02\n" +
	"\x14CreateContentRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12?\n" +
	"\ftext_content\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vtextContent\x12=\n" +
	"\fmedia_ref_id\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"mediaRefId\x12\x18\n" +
	"\aprivacy\x18\x05 \x01(\tR\aprivacy\x12:\n" +
	"\n" +
	"expiration\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x127\n" +
	"\bduration\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\bduration\"<\n" +
	"\x0fContentResponse\x12)\n" +
	"\acontent\x18\x01 \x01(\v2\x0f.api.v1.ContentR\acontent\"2\n" +
	"\x11GetContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\"5\n" +
	"\x14DeleteContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\"1\n" +
	"\x15DeleteContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x16ListUserContentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"F\n" +
	"\x17ListUserContentResponse\x12+\n" +
	"\bcontents\x18\x01 \x03(\v2\x0f.api.v1.ContentR\bcontents2\xbd\x02\n" +
	"\vFeedService\x12F\n" +
	"\rCreateContent\x12\x1c.api.v1.CreateContentRequest\x1a\x17.api.v1.ContentResponse\x12D\n" +
	"\x0eGetContentByID\x12\x19.api.v1.GetContentRequest\x1a\x17.api.v1.ContentResponse\x12L\n" +
	"\rDeleteContent\x12\x1c.api.v1.DeleteContentRequest\x1a\x1d.api.v1.DeleteContentResponse\x12R\n" +
	"\x0fListUserContent\x12\x1e.api.v1.ListUserContentRequest\x1a\x1f.api.v1.ListUserContentResponseB\rZ\v/feed;apiv1b\x06proto3"

var (
	file_feed_proto_rawDescOnce sync.Once
	file_feed_proto_rawDescData []byte
)

func file_feed_proto_rawDescGZIP() []byte {
	file_feed_proto_rawDescOnce.Do(func() {
		file_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)))
	})
	return file_feed_proto_rawDescData
}

var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_feed_proto_goTypes = []any{
	(*Content)(nil),                 // 0: api.v1.Content
	(*CreateContentRequest)(nil),    // 1: api.v1.CreateContentRequest
	(*ContentResponse)(nil),         // 2: api.v1.ContentResponse
	(*GetContentRequest)(nil),       // 3: api.v1.GetContentRequest
	(*DeleteContentRequest)(nil),    // 4: api.v1.DeleteContentRequest
	(*DeleteContentResponse)(nil),   // 5: api.v1.DeleteContentResponse
	(*ListUserContentRequest)(nil),  // 6: api.v1.ListUserContentRequest
	(*ListUserContentResponse)(nil), // 7: api.v1.ListUserContentResponse
	(*wrapperspb.StringValue)(nil),  // 8: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),   // 9: google.protobuf.Int64Value
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil),   // 11: google.protobuf.Int32Value
}
var file_feed_proto_depIdxs = []int32{
	8,  // 0: api.v1.Content.text_content:type_name -> google.protobuf.StringValue
	9,  // 1: api.v1.Content.media_ref_id:type_name -> google.protobuf.Int64Value
	10, // 2: api.v1.Content.expiration:type_name -> google.protobuf.Timestamp
	11, // 3: api.v1.Content.duration:type_name -> google.protobuf.Int32Value
	10, // 4: api.v1.Content.created_at:type_name -> google.protobuf.Timestamp
	10, // 5: api.v1.Content.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 6: api.v1.CreateContentRequest.text_content:type_name -> google.protobuf.StringValue
	9,  // 7: api.v1.CreateContentRequest.media_ref_id:type_name -> google.protobuf.Int64Value
	10, // 8: api.v1.CreateContentRequest.expiration:type_name -> google.protobuf.Timestamp
	11, // 9: api.v1.CreateContentRequest.duration:type_name -> google.protobuf.Int32Value
	0,  // 10: api.v1.ContentResponse.content:type_name -> api.v1.Content
	0,  // 11: api.v1.ListUserContentResponse.contents:type_name -> api.v1.Content
	1,  // 12: api.v1.FeedService.CreateContent:input_type -> api.v1.CreateContentRequest
	3,  // 13: api.v1.FeedService.GetContentByID:input_type -> api.v1.GetContentRequest
	4,  // 14: api.v1.FeedService.DeleteContent:input_type -> api.v1.DeleteContentRequest
	6,  // 15: api.v1.FeedService.ListUserContent:input_type -> api.v1.ListUserContentRequest
	2,  // 16: api.v1.FeedService.CreateContent:output_type -> api.v1.ContentResponse
	2,  // 17: api.v1.FeedService.GetContentByID:output_type -> api.v1.ContentResponse
	5,  // 18: api.v1.FeedService.DeleteContent:output_type -> api.v1.DeleteContentResponse
	7,  // 19: api.v1.FeedService.ListUserContent:output_type -> api.v1.ListUserContentResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
