// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/v1/feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_api_v1_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{0}
}

func (x *UserID) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ContentID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentID) Reset() {
	*x = ContentID{}
	mi := &file_api_v1_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentID) ProtoMessage() {}

func (x *ContentID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentID.ProtoReflect.Descriptor instead.
func (*ContentID) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{1}
}

func (x *ContentID) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type GetUserContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   int64                  `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	TargetUserId  int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContentRequest) Reset() {
	*x = GetUserContentRequest{}
	mi := &file_api_v1_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContentRequest) ProtoMessage() {}

func (x *GetUserContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContentRequest.ProtoReflect.Descriptor instead.
func (*GetUserContentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserContentRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetUserContentRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	MediaData     []byte                 `protobuf:"bytes,3,opt,name=media_data,json=mediaData,proto3" json:"media_data,omitempty"`
	MediaType     string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	MediaName     string                 `protobuf:"bytes,5,opt,name=media_name,json=mediaName,proto3" json:"media_name,omitempty"`
	Privacy       string                 `protobuf:"bytes,6,opt,name=privacy,proto3" json:"privacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_api_v1_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreatePostRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreatePostRequest) GetMediaData() []byte {
	if x != nil {
		return x.MediaData
	}
	return nil
}

func (x *CreatePostRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CreatePostRequest) GetMediaName() string {
	if x != nil {
		return x.MediaName
	}
	return ""
}

func (x *CreatePostRequest) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

type CreateReelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	MediaData     []byte                 `protobuf:"bytes,3,opt,name=media_data,json=mediaData,proto3" json:"media_data,omitempty"`
	MediaName     string                 `protobuf:"bytes,4,opt,name=media_name,json=mediaName,proto3" json:"media_name,omitempty"`
	DurationSecs  int32                  `protobuf:"varint,5,opt,name=duration_secs,json=durationSecs,proto3" json:"duration_secs,omitempty"`
	Privacy       string                 `protobuf:"bytes,6,opt,name=privacy,proto3" json:"privacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReelRequest) Reset() {
	*x = CreateReelRequest{}
	mi := &file_api_v1_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReelRequest) ProtoMessage() {}

func (x *CreateReelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReelRequest.ProtoReflect.Descriptor instead.
func (*CreateReelRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReelRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateReelRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *CreateReelRequest) GetMediaData() []byte {
	if x != nil {
		return x.MediaData
	}
	return nil
}

func (x *CreateReelRequest) GetMediaName() string {
	if x != nil {
		return x.MediaName
	}
	return ""
}

func (x *CreateReelRequest) GetDurationSecs() int32 {
	if x != nil {
		return x.DurationSecs
	}
	return 0
}

func (x *CreateReelRequest) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

type CreateStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	MediaName     string                 `protobuf:"bytes,3,opt,name=media_name,json=mediaName,proto3" json:"media_name,omitempty"`
	MediaData     []byte                 `protobuf:"bytes,4,opt,name=media_data,json=mediaData,proto3" json:"media_data,omitempty"`
	DurationSecs  int32                  `protobuf:"varint,5,opt,name=duration_secs,json=durationSecs,proto3" json:"duration_secs,omitempty"`
	Privacy       string                 `protobuf:"bytes,6,opt,name=privacy,proto3" json:"privacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryRequest) Reset() {
	*x = CreateStoryRequest{}
	mi := &file_api_v1_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryRequest) ProtoMessage() {}

func (x *CreateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{5}
}

func (x *CreateStoryRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateStoryRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CreateStoryRequest) GetMediaName() string {
	if x != nil {
		return x.MediaName
	}
	return ""
}

func (x *CreateStoryRequest) GetMediaData() []byte {
	if x != nil {
		return x.MediaData
	}
	return nil
}

func (x *CreateStoryRequest) GetDurationSecs() int32 {
	if x != nil {
		return x.DurationSecs
	}
	return 0
}

func (x *CreateStoryRequest) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

type ReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentId     int64                  `protobuf:"varint,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // like, love, laugh, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionRequest) Reset() {
	*x = ReactionRequest{}
	mi := &file_api_v1_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionRequest) ProtoMessage() {}

func (x *ReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionRequest.ProtoReflect.Descriptor instead.
func (*ReactionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{6}
}

func (x *ReactionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReactionRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *ReactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeleteReactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentId     int64                  `protobuf:"varint,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReactionRequest) Reset() {
	*x = DeleteReactionRequest{}
	mi := &file_api_v1_feed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReactionRequest) ProtoMessage() {}

func (x *DeleteReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteReactionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReactionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteReactionRequest) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type Reaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContentId     int64                  `protobuf:"varint,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_api_v1_feed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{8}
}

func (x *Reaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reaction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Reaction) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Reaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Reaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ReactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reactions     []*Reaction            `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionList) Reset() {
	*x = ReactionList{}
	mi := &file_api_v1_feed_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionList) ProtoMessage() {}

func (x *ReactionList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionList.ProtoReflect.Descriptor instead.
func (*ReactionList) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{9}
}

func (x *ReactionList) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type TimelineContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,5,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Privacy       string                 `protobuf:"bytes,6,opt,name=privacy,proto3" json:"privacy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineContent) Reset() {
	*x = TimelineContent{}
	mi := &file_api_v1_feed_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineContent) ProtoMessage() {}

func (x *TimelineContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineContent.ProtoReflect.Descriptor instead.
func (*TimelineContent) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{10}
}

func (x *TimelineContent) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *TimelineContent) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TimelineContent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TimelineContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TimelineContent) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *TimelineContent) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *TimelineContent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*TimelineContent     `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResponse) Reset() {
	*x = TimelineResponse{}
	mi := &file_api_v1_feed_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse) ProtoMessage() {}

func (x *TimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse.ProtoReflect.Descriptor instead.
func (*TimelineResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{11}
}

func (x *TimelineResponse) GetContents() []*TimelineContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

type FeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedResponse) Reset() {
	*x = FeedResponse{}
	mi := &file_api_v1_feed_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResponse) ProtoMessage() {}

func (x *FeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResponse.ProtoReflect.Descriptor instead.
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{12}
}

func (x *FeedResponse) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *FeedResponse) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *FeedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FeedStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedStatusResponse) Reset() {
	*x = FeedStatusResponse{}
	mi := &file_api_v1_feed_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedStatusResponse) ProtoMessage() {}

func (x *FeedStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedStatusResponse.ProtoReflect.Descriptor instead.
func (*FeedStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{13}
}

func (x *FeedStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaRefId    int64                  `protobuf:"varint,1,opt,name=media_ref_id,json=mediaRefId,proto3" json:"media_ref_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_api_v1_feed_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{14}
}

func (x *MediaResponse) GetMediaRefId() int64 {
	if x != nil {
		return x.MediaRefId
	}
	return 0
}

func (x *MediaResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *MediaResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaResponse) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	TextContent   string                 `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,5,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Privacy       string                 `protobuf:"bytes,6,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_api_v1_feed_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_feed_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_api_v1_feed_proto_rawDescGZIP(), []int{15}
}

func (x *Content) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *Content) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Content) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Content) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *Content) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Content) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *Content) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_api_v1_feed_proto protoreflect.FileDescriptor

const file_api_v1_feed_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/feed.proto\x12\vapi.v1.feed\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"*\n" +
	"\tContentID\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\"`\n" +
	"\x15GetUserContentRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\x03R\vrequesterId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"\xbb\x01\n" +
	"\x11CreatePostRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"media_data\x18\x03 \x01(\fR\tmediaData\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"media_name\x18\x05 \x01(\tR\tmediaName\x12\x18\n" +
	"\aprivacy\x18\x06 \x01(\tR\aprivacy\"\xc7\x01\n" +
	"\x11CreateReelRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x1d\n" +
	"\n" +
	"media_data\x18\x03 \x01(\fR\tmediaData\x12\x1d\n" +
	"\n" +
	"media_name\x18\x04 \x01(\tR\tmediaName\x12#\n" +
	"\rduration_secs\x18\x05 \x01(\x05R\fdurationSecs\x12\x18\n" +
	"\aprivacy\x18\x06 \x01(\tR\aprivacy\"\xcd\x01\n" +
	"\x12CreateStoryRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"media_name\x18\x03 \x01(\tR\tmediaName\x12\x1d\n" +
	"\n" +
	"media_data\x18\x04 \x01(\fR\tmediaData\x12#\n" +
	"\rduration_secs\x18\x05 \x01(\x05R\fdurationSecs\x12\x18\n" +
	"\aprivacy\x18\x06 \x01(\tR\aprivacy\"]\n" +
	"\x0fReactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x03R\tcontentId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"O\n" +
	"\x15DeleteReactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x03R\tcontentId\"\xa1\x01\n" +
	"\bReaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\x03R\tcontentId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"C\n" +
	"\fReactionList\x123\n" +
	"\treactions\x18\x01 \x03(\v2\x15.api.v1.feed.ReactionR\treactions\"\xe7\x01\n" +
	"\x0fTimelineContent\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1b\n" +
	"\tmedia_url\x18\x05 \x01(\tR\bmediaUrl\x12\x18\n" +
	"\aprivacy\x18\x06 \x01(\tR\aprivacy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"L\n" +
	"\x10TimelineResponse\x128\n" +
	"\bcontents\x18\x01 \x03(\v2\x1c.api.v1.feed.TimelineContentR\bcontents\"d\n" +
	"\fFeedResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\".\n" +
	"\x12FeedStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xaa\x01\n" +
	"\rMediaResponse\x12 \n" +
	"\fmedia_ref_id\x18\x01 \x01(\x03R\n" +
	"mediaRefId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12;\n" +
	"\vuploaded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\xd1\x01\n" +
	"\aContent\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\x03R\tcontentId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\ftext_content\x18\x04 \x01(\tR\vtextContent\x12\x1b\n" +
	"\tmedia_url\x18\x05 \x01(\tR\bmediaUrl\x12\x18\n" +
	"\aprivacy\x18\x06 \x01(\tR\aprivacy\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp2\xbb\x06\n" +
	"\vFeedService\x12G\n" +
	"\n" +
	"CreatePost\x12\x1e.api.v1.feed.CreatePostRequest\x1a\x19.api.v1.feed.FeedResponse\x12G\n" +
	"\n" +
	"CreateReel\x12\x1e.api.v1.feed.CreateReelRequest\x1a\x19.api.v1.feed.FeedResponse\x12I\n" +
	"\vCreateStory\x12\x1f.api.v1.feed.CreateStoryRequest\x1a\x19.api.v1.feed.FeedResponse\x12O\n" +
	"\x0eReactToContent\x12\x1c.api.v1.feed.ReactionRequest\x1a\x1f.api.v1.feed.FeedStatusResponse\x12A\n" +
	"\fGetReactions\x12\x16.api.v1.feed.ContentID\x1a\x19.api.v1.feed.ReactionList\x12U\n" +
	"\x0eDeleteReaction\x12\".api.v1.feed.DeleteReactionRequest\x1a\x1f.api.v1.feed.FeedStatusResponse\x12A\n" +
	"\vGetTimeline\x12\x13.api.v1.feed.UserID\x1a\x1d.api.v1.feed.TimelineResponse\x12S\n" +
	"\x0eGetUserContent\x12\".api.v1.feed.GetUserContentRequest\x1a\x1d.api.v1.feed.TimelineResponse\x12A\n" +
	"\vGetMediaRef\x12\x16.api.v1.feed.ContentID\x1a\x1a.api.v1.feed.MediaResponse\x12?\n" +
	"\n" +
	"GetContent\x12\x16.api.v1.feed.ContentID\x1a\x19.api.v1.feed.FeedResponse\x12H\n" +
	"\rDeleteContent\x12\x16.api.v1.feed.ContentID\x1a\x1f.api.v1.feed.FeedStatusResponseB\x12Z\x10api/v1/feed;feedb\x06proto3"

var (
	file_api_v1_feed_proto_rawDescOnce sync.Once
	file_api_v1_feed_proto_rawDescData []byte
)

func file_api_v1_feed_proto_rawDescGZIP() []byte {
	file_api_v1_feed_proto_rawDescOnce.Do(func() {
		file_api_v1_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_feed_proto_rawDesc), len(file_api_v1_feed_proto_rawDesc)))
	})
	return file_api_v1_feed_proto_rawDescData
}

var file_api_v1_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_v1_feed_proto_goTypes = []any{
	(*UserID)(nil),                // 0: api.v1.feed.UserID
	(*ContentID)(nil),             // 1: api.v1.feed.ContentID
	(*GetUserContentRequest)(nil), // 2: api.v1.feed.GetUserContentRequest
	(*CreatePostRequest)(nil),     // 3: api.v1.feed.CreatePostRequest
	(*CreateReelRequest)(nil),     // 4: api.v1.feed.CreateReelRequest
	(*CreateStoryRequest)(nil),    // 5: api.v1.feed.CreateStoryRequest
	(*ReactionRequest)(nil),       // 6: api.v1.feed.ReactionRequest
	(*DeleteReactionRequest)(nil), // 7: api.v1.feed.DeleteReactionRequest
	(*Reaction)(nil),              // 8: api.v1.feed.Reaction
	(*ReactionList)(nil),          // 9: api.v1.feed.ReactionList
	(*TimelineContent)(nil),       // 10: api.v1.feed.TimelineContent
	(*TimelineResponse)(nil),      // 11: api.v1.feed.TimelineResponse
	(*FeedResponse)(nil),          // 12: api.v1.feed.FeedResponse
	(*FeedStatusResponse)(nil),    // 13: api.v1.feed.FeedStatusResponse
	(*MediaResponse)(nil),         // 14: api.v1.feed.MediaResponse
	(*Content)(nil),               // 15: api.v1.feed.Content
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_api_v1_feed_proto_depIdxs = []int32{
	16, // 0: api.v1.feed.Reaction.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: api.v1.feed.ReactionList.reactions:type_name -> api.v1.feed.Reaction
	16, // 2: api.v1.feed.TimelineContent.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: api.v1.feed.TimelineResponse.contents:type_name -> api.v1.feed.TimelineContent
	16, // 4: api.v1.feed.MediaResponse.uploaded_at:type_name -> google.protobuf.Timestamp
	3,  // 5: api.v1.feed.FeedService.CreatePost:input_type -> api.v1.feed.CreatePostRequest
	4,  // 6: api.v1.feed.FeedService.CreateReel:input_type -> api.v1.feed.CreateReelRequest
	5,  // 7: api.v1.feed.FeedService.CreateStory:input_type -> api.v1.feed.CreateStoryRequest
	6,  // 8: api.v1.feed.FeedService.ReactToContent:input_type -> api.v1.feed.ReactionRequest
	1,  // 9: api.v1.feed.FeedService.GetReactions:input_type -> api.v1.feed.ContentID
	7,  // 10: api.v1.feed.FeedService.DeleteReaction:input_type -> api.v1.feed.DeleteReactionRequest
	0,  // 11: api.v1.feed.FeedService.GetTimeline:input_type -> api.v1.feed.UserID
	2,  // 12: api.v1.feed.FeedService.GetUserContent:input_type -> api.v1.feed.GetUserContentRequest
	1,  // 13: api.v1.feed.FeedService.GetMediaRef:input_type -> api.v1.feed.ContentID
	1,  // 14: api.v1.feed.FeedService.GetContent:input_type -> api.v1.feed.ContentID
	1,  // 15: api.v1.feed.FeedService.DeleteContent:input_type -> api.v1.feed.ContentID
	12, // 16: api.v1.feed.FeedService.CreatePost:output_type -> api.v1.feed.FeedResponse
	12, // 17: api.v1.feed.FeedService.CreateReel:output_type -> api.v1.feed.FeedResponse
	12, // 18: api.v1.feed.FeedService.CreateStory:output_type -> api.v1.feed.FeedResponse
	13, // 19: api.v1.feed.FeedService.ReactToContent:output_type -> api.v1.feed.FeedStatusResponse
	9,  // 20: api.v1.feed.FeedService.GetReactions:output_type -> api.v1.feed.ReactionList
	13, // 21: api.v1.feed.FeedService.DeleteReaction:output_type -> api.v1.feed.FeedStatusResponse
	11, // 22: api.v1.feed.FeedService.GetTimeline:output_type -> api.v1.feed.TimelineResponse
	11, // 23: api.v1.feed.FeedService.GetUserContent:output_type -> api.v1.feed.TimelineResponse
	14, // 24: api.v1.feed.FeedService.GetMediaRef:output_type -> api.v1.feed.MediaResponse
	12, // 25: api.v1.feed.FeedService.GetContent:output_type -> api.v1.feed.FeedResponse
	13, // 26: api.v1.feed.FeedService.DeleteContent:output_type -> api.v1.feed.FeedStatusResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_feed_proto_init() }
func file_api_v1_feed_proto_init() {
	if File_api_v1_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_feed_proto_rawDesc), len(file_api_v1_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_feed_proto_goTypes,
		DependencyIndexes: file_api_v1_feed_proto_depIdxs,
		MessageInfos:      file_api_v1_feed_proto_msgTypes,
	}.Build()
	File_api_v1_feed_proto = out.File
	file_api_v1_feed_proto_goTypes = nil
	file_api_v1_feed_proto_depIdxs = nil
}
